In [1]:
##### Initialize Processing
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.utils import np_utils

Using TensorFlow backend.


In [2]:
##### Take/Split Data
(x0_train, y0_train), (x0_test, y0_test) = mnist.load_data()
x_train = x0_train.reshape(60000, 28*28)
x_test = x0_test.reshape(10000, 28*28)
y_train = np_utils.to_categorical(y0_train,10)
y_test = np_utils.to_categorical(y0_test,10)

In [3]:
###### Building Network
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [4]:
### initialize the model
model = Sequential()

In [5]:
### build first layer
model.add(Dense(units=500, input_dim=784))
model.add(Activation('sigmoid'))

In [6]:
### build second layer
model.add(Dense(units=500))
model.add(Activation('sigmoid'))

In [7]:
### build third layer
model.add(Dense(units=10))
model.add(Activation('softmax'))

In [ ]:
### Compile the model
model.compile(loss='mse', optimizer=SGD(lr=0.1), metrics=['accuracy'])

In [ ]:
### Start training
model.fit(x_train, y_train, batch_size=100, epochs=20)


In [13]:
### Take a trained model
from ipywidgets import interact_manual
import h5py

In [14]:
result = model.predict_classes(x_test)

 9376/10000 [===========================>..] - ETA: 0s

In [15]:
def 辨識(測試編號):
    plt.imshow(x0_test[測試編號], cmap="Greys")
    print("神經網路判斷為:", result[測試編號])

In [16]:
interact_manual(辨識, 測試編號 = (0, 9999));

Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"


In [17]:
### Save model
model_json = model.to_json()
open('handwriting_model_architecture.json', 'w').write(model_json)
model.save_weights('handwriting_model_weights.h5')

In [42]:
##### practice convolution
import numpy as np
from scipy.ndimage.filters import maximum_filter

In [28]:
a = np.array([[0,0,0,0,0,0],
              [0,2,1,3,4,0],
              [0,0,2,5,1,0],
              [0,6,1,3,7,0],
              [0,1,1,1,0,0],
              [0,0,0,0,0,0]])

In [29]:
k1 = np.array([[1,0,1],
              [-1,1,1],
               [1,2,1]])

In [30]:
k2 = np.array([[1,1,2],
               [0,-1,1],
               [2,2,1]])

In [31]:
a

array([[0, 0, 0, 0, 0, 0],
       [0, 2, 1, 3, 4, 0],
       [0, 0, 2, 5, 1, 0],
       [0, 6, 1, 3, 7, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [32]:
element_filter1 = np.array([[0,0,0,0],
                            [0,0,0,0],
                            [0,0,0,0],
                            [0,0,0,0]])
element_filter2 = np.array([[0,0,0,0],
                            [0,0,0,0],
                            [0,0,0,0],
                            [0,0,0,0]])
for ind_y in range(1,5,1):
    for ind_x in range(1,5,1):
        element = a[(ind_y-1):(ind_y+2),(ind_x-1):(ind_x+2)]
        element_filter1_buf = (element*k1).sum()
        element_filter2_buf = (element*k2).sum()
        element_filter1[(ind_y-1),(ind_x-1)] = element_filter1_buf
        element_filter2[(ind_y-1),(ind_x-1)] = element_filter2_buf        

In [33]:
element_filter1

array([[ 5, 11, 19,  8],
       [16, 23, 23, 16],
       [12,  7, 15, 10],
       [ 3, 10,  8,  2]])

In [34]:
element_filter2

array([[ 1, 11, 16,  8],
       [19, 29, 23, 26],
       [ 2, 19, 17,  1],
       [ 8, 13, 17, 10]])

In [60]:
max_pooling1 = np.array([[0,0],
                        [0,0]])
max_pooling2 = np.array([[0,0],
                        [0,0]])
### try max pooling
for ind_y in range(0,2,1):
    for ind_x in range(0,2,1):
        max_pooling1[(ind_y),(ind_x)] = element_filter1[(3*ind_y):(3*ind_y+2),
                                                        (3*ind_x):(3*ind_x+2)].max()
        max_pooling2[(ind_y),(ind_x)] = element_filter2[(3*ind_y):(3*ind_y+2),
                                                        (3*ind_x):(3*ind_x+2)].max()


In [61]:
max_pooling1

array([[23, 16],
       [10,  2]])

In [62]:
max_pooling2

array([[29, 26],
       [13, 10]])