In [16]:
import numpy as np
###
x = np.array([1.3,-0.3])
h1 = 1/(1+np.exp(x))

<img src="image/RNN-single-neuron.png" alt="RNN-single-neuron" width="300">
<img src="image/RNN.png" alt="RNN" width="300">
<img src="image/RNN-with-weight.png" alt="RNN-with-weight" width="300">

In [110]:
h0 =  np.matrix([[0],[0]])
x1 = np.matrix([[1],[0],[0]])
x2 = np.matrix([[0],[1],[0]])
x3 = np.matrix([[0],[0],[1]])
x_set = np.matrix([[1,0,0],
                  [0,1,0],
                  [0,0,1]])
## transition matrix of hidden layer
Wh = np.matrix([[1,0.2],
              [1,0.2]])
## weighted matrix
Wx = np.matrix([[1,1,1],
              [-1,-1,-1]])
## bias matrix
b = np.matrix([[0.3],
              [0.7]])
## emission
EM = np.matrix([[0.3,0.2],
                [  1,-1],
                [0.3,1]])

In [333]:

def input_operation(input_list, previous_input):
        print("input:")
        print(str(input_list.transpose()))
        result = Wh*(previous_input) + Wx*(input_list) + b
        print("output")
        print(str(result))
        return result

def sigmoid(input_list):
    exp_term = np.exp(-input_list)
    sigmoid_result = 1/(1+exp_term)
    print("sigmoid")
    print(str(sigmoid_result))
    return(sigmoid_result)

def softmax(input_list):
    exp_term = np.exp(input_list)
    softmax_result = exp_term/(exp_term.sum())
    print("softmax")
    print(str(softmax_result))    
    return(softmax_result)

def emission(input_list):
    emission_result = (EM*(input_list))+0.5
    print("Emission output:") 
    print(str(emission_result))
    return emission_result

def prediction(softmax_result, basis_stack):
    output_stack = [[],[],[]]
    ind = 0
    for word in softmax_result:
        candidate = 0
        comparision_buf = 0
        for index, probability in enumerate(word):
            if probability>comparision_buf:
                candidate = index
        output_stack[ind] = basis_stack[index].transpose()
        ind += 1
    print(output_stack)
    return output_stack

In [334]:
out1 = input_operation(x1, h0)
h1 = sigmoid(out1)
EMh1 = emission(h1)
softmax1 = softmax(EMh1)

input:
[[1 0 0]]
output
[[ 1.3]
 [-0.3]]
sigmoid
[[ 0.78583498]
 [ 0.42555748]]
Emission output:
[[ 0.82086199]
 [ 0.8602775 ]
 [ 1.16130798]]
softmax
[[ 0.29021031]
 [ 0.30187752]
 [ 0.40791216]]


In [335]:
out2 = input_operation(x2, h1)
h2 = sigmoid(out2)
EMh2 = emission(h2)
softmax2 = softmax(EMh2)

input:
[[0 1 0]]
output
[[ 2.17094648]
 [ 0.57094648]]
sigmoid
[[ 0.89760999]
 [ 0.63898154]]
Emission output:
[[ 0.8970793 ]
 [ 0.75862845]
 [ 1.40826454]]
softmax
[[ 0.28264779]
 [ 0.24610313]
 [ 0.47124908]]


In [336]:
out3 = input_operation(x3, h2)
h3 = sigmoid(out3)
EMh3 = emission(h3)
softmax3 = softmax(EMh3)

input:
[[0 0 1]]
output
[[ 2.3254063]
 [ 0.7254063]]
sigmoid
[[ 0.91095943]
 [ 0.67379641]]
Emission output:
[[ 0.90804711]
 [ 0.73716303]
 [ 1.44708424]]
softmax
[[ 0.28111408]
 [ 0.23695648]
 [ 0.48192944]]


In [337]:
predicted_result = prediction([softmax1,softmax2,softmax3],[x1,x2,x3])

[matrix([[0, 0, 1]]), matrix([[0, 0, 1]]), matrix([[0, 0, 1]])]


In [338]:
predicted_result

[matrix([[0, 0, 1]]), matrix([[0, 0, 1]]), matrix([[0, 0, 1]])]

In [339]:
#######
#######
class naive_RNN:
    #### initialized the RNN
    def __init__(self, initialized_inner_input):
        self.inner_input = initialized_inner_input
        ## transition matrix of hidden layer
        self.Wh = np.matrix([[1,0.2],
                             [1,0.2]])
        ## weighted matrix
        self.Wx = np.matrix([[1,1,1],
                             [-1,-1,-1]])
        ## bias matrix
        self.bias = np.matrix([[0.3],
                               [0.7]])
        ## emission
        self.emission_matrix = np.matrix([[0.3,0.2],
                                    [  1,-1],
                                    [0.3,1]])
        ## buf for result
        self.input_mapping = 0
        self.sigmoid_result = 0
        self.softmax_result = 0
        self.emission_result = 0
        self.output_stack = []
        self.basis_stack = []
    #### input layer mapping
    def input_operation(self, input_vector):
        print("input:")
        print(str(input_vector.transpose()))
        result = self.Wh*(self.inner_input) + self.Wx*(input_vector) + self.bias
        print("output")
        print(str(result))
        self.input_mapping = result
        self.basis_stack = self.basis_stack.append(input_vector)
        #print(str(self.basis_stack))

    def sigmoid(self):
        exp_term = np.exp(-self.input_mapping)
        sigmoid_result = 1/(1+exp_term)
        print("sigmoid")
        print(str(sigmoid_result))
        self.inner_input = sigmoid_result
        self.sigmoid_result = (sigmoid_result)
        
    def emission(self):
        emission_result = (self.emission_matrix*(self.sigmoid_result))+0.5
        print("Emission output:") 
        print(str(emission_result))
        self.emission = emission_result
        
    def softmax(self):
        exp_term = np.exp(self.emission)
        softmax_result = exp_term/(exp_term.sum())
        print("softmax")
        print(str(softmax_result))    
        self.softmax_result = (softmax_result)

    def prediction(self):
        for word in self.softmax_result:
            candidate = 0
            comparision_buf = 0
            for index, probability in enumerate(word):
                if probability>comparision_buf:
                    candidate = index
            self.output_stack = self.output_stack.append(self.basis_stack[index])
        print(self.output_stack)


In [340]:
NaiveRNN = naive_RNN(h0)

In [341]:
NaiveRNN.input_operation(x1)
NaiveRNN.sigmoid()
NaiveRNN.emission()
NaiveRNN.softmax()

input:
[[1 0 0]]
output
[[ 1.3]
 [-0.3]]
sigmoid
[[ 0.78583498]
 [ 0.42555748]]
Emission output:
[[ 0.82086199]
 [ 0.8602775 ]
 [ 1.16130798]]
softmax
[[ 0.29021031]
 [ 0.30187752]
 [ 0.40791216]]
